/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visual;

import java.awt.Color;
import org.json.JSONArray;
import gestionalimentos.Pedido;
import supabase.Supabase;
import Modelo.Conexion;

/**
 *
 * @author User
 */
public class GenerarPedido extends javax.swing.JPanel {

    /**
     * Creates new form GenerarPedido
     */
    public GenerarPedido(Supabase sup) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanIzqui = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BoxVege = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BoxCarne = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BocGuarni = new javax.swing.JComboBox<>();
        PanDere = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BoxBebida = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BoxPostre = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        ErrorPedido = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        PanIzqui.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        PanIzqui.setPreferredSize(new java.awt.Dimension(0, 0));
        PanIzqui.setLayout(new java.awt.GridLayout(4, 0, 0, 25));

        jPanel7.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jLabel6.setText("Ingrese el nombre del comensal:");
        jPanel7.add(jLabel6);
        jPanel7.add(TxtNombre);

        PanIzqui.add(jPanel7);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jLabel1.setText("Seleccione Una Verdura:");
        jPanel1.add(jLabel1);

        BoxVege.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lechuga", "Tomate", "Cebolla", "Ajo", "Pimientos" }));
        jPanel1.add(BoxVege);

        PanIzqui.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jLabel2.setText("Selecciones una carne para la comida principal:");
        jPanel2.add(jLabel2);

        BoxCarne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Res", "Cerdo", "Pollo", "Pato", "Pavo" }));
        jPanel2.add(BoxCarne);

        PanIzqui.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jLabel3.setText("Seleccione la Guarnicion de la carne:");
        jPanel3.add(jLabel3);

        BocGuarni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasta", "Arroz", "Papas", "Tostada", "Platano", " ", " " }));
        jPanel3.add(BocGuarni);

        PanIzqui.add(jPanel3);

        add(PanIzqui);

        PanDere.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        PanDere.setPreferredSize(new java.awt.Dimension(0, 0));
        PanDere.setLayout(new java.awt.GridLayout(4, 0, 0, 25));

        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jLabel4.setText("Seleccione una bebida");
        jPanel4.add(jLabel4);

        BoxBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vino", "Cerveza", "Gaseosa", "Agua", "Jugo", " " }));
        jPanel4.add(BoxBebida);

        PanDere.add(jPanel4);

        jPanel6.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jLabel5.setText("Seleecione un postre");
        jPanel6.add(jLabel5);

        BoxPostre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Helado", "Trasta", "Fresas Con Crema", " " }));
        jPanel6.add(BoxPostre);

        PanDere.add(jPanel6);

        jButton1.setText("Generar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanDere.add(jButton1);

        ErrorPedido.setForeground(new java.awt.Color(255, 0, 0));
        PanDere.add(ErrorPedido);

        add(PanDere);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String nombre, vegetal, carne, guarnicion, bebida, postre;
               
        nombre=TxtNombre.getText();
        vegetal=BoxVege.getSelectedItem().toString();
        carne=BoxCarne.getSelectedItem().toString();
        guarnicion=BocGuarni.getSelectedItem().toString();
        bebida=BoxBebida.getSelectedItem().toString();
        postre=BoxPostre.getSelectedItem().toString();

        if (nombre.isEmpty()){
            ErrorPedido.setText("Ingrese el nombre del comensal");
            return;
        }
        
        Conexion.GenerarPed(nombre, vegetal, carne, guarnicion, bebida, postre);
        
        TxtNombre.setText("");
        ErrorPedido.setText("Usuario creado correctamente SU PEDIDO ES: " + nombre + vegetal + carne + guarnicion + bebida + postre);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BocGuarni;
    private javax.swing.JComboBox<String> BoxBebida;
    private javax.swing.JComboBox<String> BoxCarne;
    private javax.swing.JComboBox<String> BoxPostre;
    private javax.swing.JComboBox<String> BoxVege;
    private javax.swing.JLabel ErrorPedido;
    private javax.swing.JPanel PanDere;
    private javax.swing.JPanel PanIzqui;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
